### ISSUE TITLE
Where else can you improve your dynamic group convolution?

### ISSUE THREAD

**Issue by longmalongma** [zhuogege1943/dgc#10]
Where else can you improve your dynamic group convolution?

**Comment by hellozhuo** [comment]
> Where else can you improve your dynamic group convolution?

Hi thanks for your question, I am thinking how to make the DGC be more dynamic, i.e., dynamically allocate different amount of computation resources according to the difficulties of input images, which could be done by pruning different number of channels adaptive to the input. Now, the allocated computation resource is the same for all images.

**Comment by longmalongma** [comment]
> dynamically allocate different amount of computation resources according to the difficulties of input images, which could be done by pruning different number of channels adaptive to the input.

Thanks for your reply, do you mean you want to prune the out channels adaptively?

**Comment by hellozhuo** [comment]
> > dynamically allocate different amount of computation resources according to the difficulties of input images, which could be done by pruning different number of channels adaptive to the input.
> 
> Thanks for your reply, do you mean you want to prune the out channels adaptively?

I think pruning either input channels or output channels adaptively could be fine.

**Comment by longmalongma** [comment]
> > > dynamically allocate different amount of computation resources according to the difficulties of input images, which could be done by pruning different number of channels adaptive to the input.
> > 
> > 
> > Thanks for your reply, do you mean you want to prune the out channels adaptively?
> 
> I think pruning either input channels or output channels adaptively could be fine.

Thanks！
