### ISSUE TITLE
How to implement global threshold 6.1 

### ISSUE THREAD

**Issue by lizhenstat** [zhuogege1943/dgc#2]
Hi, thanks for your work and release of your code! 
I have two questions related to section 6.1 on global threshold:
(1) Equation(9) concat saliency vectors from different layers together, is saliency vector comparable to each other from different layers?
(2) How do you implement this in code?

thanks

**Comment by hellozhuo** [comment]
@lizhenstat Question 1 is a good question. The answer could be found through Fig. 10 in section 6.3, where the actual prunning rates in different layers are in a normal range. That means these saliency vectors are comparable among layers. E.g., if the saliencies in a layer is far smaller than others, then the prunning rate in this layer would be close to 0. 
For the 2nd qeustion, what we did is defining a global variable to collect these vectors to combine into a huge single vector through N iterations, then rank the elements in this big vector, take the element at the target percentile position as the global threshold. The process could be done in the last N iterations for each epoch.
