### ISSUE TITLE
Question on angle enlargement in Section 6.1

### ISSUE THREAD

**Issue by lizhenstat** [zhuogege1943/dgc#3]
Hi, thanks for your work.

I have two questions on angle enlargement part, 
(1) the paper said **Our experiments show that it is automatically achieved during training if head-wise threshold is adopted, 
     adding such loss hardly gives any improvement on the performance**
     since different head is pruned independently, why this result in diversity between groups.

(2)Besides, I noticed different the following results:

     Cifar10: 4.77(CondenseNet-86-DGC) & 4.42(CondenseNet-86-DGC-G) [from Table 3]
     Cifar100: 23.41(CondenseNet-86-DGC) & 23.36(CondenseNet-86-DGC-G) [from Table 3]
     ImageNet: 25.4(CondenseNet-86-DGC) & 25.2(CondenseNet-86-DGC-G) [from Table2]

Have you tested global threshold without this angle enlargement trick?
Since I am wondering whether this model performance boost comes from the third loss(equation(11)) 
or the global threshold pruning schedule. 

Thanks a lot!

**Comment by hellozhuo** [comment]
@lizhenstat Thanks for your interests. We have conducted the comparison experiments with and without the angle trick on head-wise threshold, showing there is no performance boost (results are the same for Imagenet ). Fig. 9 also shows the diversity between heads, so the angle trick seems unnecessary for head-wise threshold.  To explain the reason behind this, we need further exploration.
While for global threshold method, without the andgle loss, thre results would be obviously worse (Imagenet: 25.8 on CondenseNet-DGC-G without angle loss). So for the global method, the performance boost may come from the third loss.

**Comment by lizhenstat** [comment]
@zhuogege1943 Hi, thanks for your detailed reply, it seems that this angle loss is a good regularization method. 👍 :
