### ISSUE TITLE
Can you provide your codes based on tensorflow?

### ISSUE THREAD

**Issue by longmalongma** [zhuogege1943/dgc#8]
Hi, thanks for your good work. Can you provide your codes based on TensorFlow?

**Comment by hellozhuo** [comment]
Hi. We didn't have the TensorFlow code. Sorry for that.

**Comment by longmalongma** [comment]
> Hi. We didn't have the TensorFlow code. Sorry for that.


How to implement the module DynamicMultiHeadConv based on tensorflow? Because my codes is based on tensorflow, I want to introduce your DynamicMultiHeadConv and cite your paper. can you provider your codes about your module DynamicMultiHeadConv based on tensorflow? looking forward to your reply.

**Comment by hellozhuo** [comment]
> > Hi. We didn't have the TensorFlow code. Sorry for that.
> 
> How to implement the module DynamicMultiHeadConv based on tensorflow? Because my codes is based on tensorflow, I want to introduce your DynamicMultiHeadConv and cite your paper. can you provider your codes about your module DynamicMultiHeadConv based on tensorflow? looking forward to your reply.

Thanks for your interests. To be frank, the last time I used Tensorflow was two years ago, I am afraid I have to dust off and relearn some of the concepts to implement that and I donot have enough time. Best if you can do that by yourself.

**Comment by longmalongma** [comment]
> > > Hi. We didn't have the TensorFlow code. Sorry for that.
> > 
> > 
> > How to implement the module DynamicMultiHeadConv based on tensorflow? Because my codes is based on tensorflow, I want to introduce your DynamicMultiHeadConv and cite your paper. can you provider your codes about your module DynamicMultiHeadConv based on tensorflow? looking forward to your reply.
> 
> Thanks for your interests. To be frank, the last time I used Tensorflow was two years ago, I am afraid I have to dust off and relearn some of the concepts to implement that and I donot have enough time. Best if you can do that by yourself.

Thanks.
